### ISSUE TITLE
Secondary display only shows pointer

### ISSUE THREAD

**Issue by carlpett** [emersion/kanshi#103]
_(Not sure if this is a problem with kanshi or Sway, sorry)_

When plugging in an external display, kanshi correctly detects it, but the only thing shown is the mouse pointer. `swaymsg -t get_outputs` shows the output, and claims a workspace is active on it. However, moving containers there, or starting applications, they do not render anything. Just the pointer (which renders movement etc correctly).

I'm not sure how to troubleshoot - the basics of activating the screen, and positioning etc all work, but not the actual functionality.

I'm running Sway 1.6 (From Fedora package sway-1.6-1.fc34.src.rpm), and kanshi 1.1.0 (kanshi-1.1.0-3.fc34.src.rpm).

Configuration:
```
profile "Dual" {
  output eDP-1
  output "Dell Inc. DELL P2419H 4S86K43"
}
profile "Laptop only" {
  output eDP-1
}
```

Hardware is a Thinkpad X1 Extreme Gen3, connecting with the external screen over HDMI. 

Let me know if there's anything else I should have provided, I'm still very new to Sway.

**Comment by emersion** [comment]
Can you open a Sway issue? This doesn't sound like a kanshi bug.
