### ISSUE TITLE
Man pages

### ISSUE THREAD

**Issue by emersion** [emersion/kanshi#12]
Document the config file format and the `kanshi` command.

**Comment by prometheanfire** [comment]
also the readme (I still don't know it's usage, is it a toggle or selection (or both))?

**Comment by varac** [comment]
Yes please, I'm staring at the README.md for a while now and have only half a clue how I can use kanshi.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/kanshi/commit/4b16771942ee394ca79c2eb46cec80fe8acb753a
