### ISSUE TITLE
Add support for transform (i.e rotation)

### ISSUE THREAD

**Issue by MaxBullett** [emersion/kanshi#17]
Hi there,

Great job you're doing here.
Adding `transform 90` (sway screen rotation) to an output in `.config/kanshi/config` causes the parser to silently fail. Upon inspection, I noticed the frontend and store don't seem to handle screen rotation. I think this would be fairly easy addition and much appreciated feature for portrait output lovers.

Cheers,

**Comment by emersion** [comment]
>Great job you're doing here.

Glad you like it!

>causes the parser to silently fail.

Yeah, this is annoying. I plan to rewrite the parser (https://github.com/emersion/kanshi/issues/18).

>Upon inspection, I noticed the frontend and store don't seem to handle screen rotation. I think this would be fairly easy addition and much appreciated feature for portrait output lovers.

Yes! Would you be willing to send a PR?

**Comment by MaxBullett** [comment]
Yeah sure. I haven't written anything yet and am fairly new to this but it doesn't look too tough (famous last words). I'll give it a fork over the weekend.
