### ISSUE TITLE
kanshi produces the wrong parameters for position on sway

### ISSUE THREAD

**Issue by MichaelAquilina** [emersion/kanshi#25]
My configuration produces
```
$ kanshi 2>/dev/null
output eDP-1 disable
output DP-1 position 0,0 scale 1
```

If I try running the second line:
```
$ swaymsg "output DP-1 position 0,0 scale 1"
Error: Missing position argument (y).
```

This seems to be because position is marked as `x,y` rather than `x y`. The documentation on `man sway-output` specifies that x and y should be separated by a space and using a space instead seems to work:

```
$ swaymsg 'output DP-1 position 0 0'
<no error message>
```

**Comment by MichaelAquilina** [comment]
My cofiguration file:
```
{
    output eDP-1 scale 2
}
{
    output eDP-1 disable
    output DP-1 scale 1
}
```

**Comment by emersion** [comment]
Can you send a patch?

**Comment by MichaelAquilina** [comment]
Hmmm perhaps the version that is published on the rust crates index is very out of date? The issue doesnt seem to be present when compiling it manually from github.

**Comment by MichaelAquilina** [comment]
However an issue with the latest version seems to be that it doesnt recognize my configuration correctly. Debugging this right now but I am a bit unfamiliar with the `named!` syntax you are using in `store.rs`

**Comment by luispabon** [comment]
Facing this same issue, installed from cargo. Would it be possible to update the crate please? Last version in there is from 2017.
