### ISSUE TITLE
Invalid monitors.xml format

### ISSUE THREAD

**Issue by BlueGone** [emersion/kanshi#26]
My monitors.xml, which is generated by gnome, doesn't seem to match the XML tree expected by the code.

My `monitors.xml` is the following :
```
<monitors version="2">
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-1</connector>
          <vendor>AOC</vendor>
          <product>2460G5</product>
          <serial>0x00000a03</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000495910644531</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>1080</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>CMN</vendor>
          <product>0x14c0</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.008350372314453</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>
```

The GnomeStore expect to find some elements named `output` inside a `configuration`, but as we can see, there is none.

**Comment by emersion** [comment]
GNOME have updated their `monitors.xml` to use a new schema some time ago.

**Comment by BlueGone** [comment]
Ok. Do you know if a documentation exist for this file by Gnome ? I don't find one.

**Comment by emersion** [comment]
There was some wiki page iirc, but it's probably outdated now.

**Comment by BlueGone** [comment]
Can I freely implement the last version, or must I care about backward compatibility ?

**Comment by emersion** [comment]
TBH I'm not a fan of supporting GNOME's private config file anymore. What would be your use-case?

Also a complete rewrite of this project is planned...

**Comment by BlueGone** [comment]
My use case is that I use both GNOME and Sway. So having a common configuration is nice for me. But I understand the fact that it is not desirable to support GNOME's config file. I can do without.
