### ISSUE TITLE
Compositor doesn't support wlr-output-management-unstable-v1

### ISSUE THREAD

**Issue by luispabon** [emersion/kanshi#31]
I'm trying to run the C rewrite in Ubuntu Disco. For Sway and wlroots, I'm using the ppa here https://launchpad.net/~samoilov-lex/+archive/ubuntu/sway. I've compiled the kanshi binary locally in a docker container.

Upon running,  kanshi exits with:
```
compositor doesn't support wlr-output-management-unstable-v1
```

config:
```
{
    output "Sharp Corporation 0x1476 0x00000000" mode 3840x2160 scale 2 position 0,0
}
```

**Comment by emersion** [comment]
This needs the latest sway commit. wlr-output-management-v1 has been added recently to sway.

If this is an issue, you can stick to the Rust version temporarily.

**Comment by luispabon** [comment]
Thank you, I can live without for a bit no probs.
