### ISSUE TITLE
Config file comment support

### ISSUE THREAD

**Issue by luispabon** [emersion/kanshi#33]
I'm going to have a fairly large config file as I move my laptop around quite a lot (home, desk@office, meeting room etc). It would be great if the config file would accept comments so that I could identify each block.

**Comment by btaczala** [comment]
Pull request here: https://github.com/emersion/kanshi/pull/50

**Comment by emersion** [comment]
Implemented in https://github.com/emersion/kanshi/pull/50

**Comment by luispabon** [comment]
Super, thank you :+1:
