### ISSUE TITLE
set background using kanshi

### ISSUE THREAD

**Issue by sanga** [emersion/kanshi#41]
I would like to be able to set the background as if I start sway without my external monitor set up any directive (i.e. setting the background) for the ext monitor won't get applied. Kanshi could do this I guess but doesn't currently support it.

```
conf file
{
    output eDP-1 background /home/tsampson/Wallpapers/Mount-Cook-New-Zealand1-2560x1440.jpg center
}

kanshi:
unknown directive 'background' in profile output 'eDP-1'
failed to parse config file: error on line 2, column 28

```

**Comment by emersion** [comment]
Why do you need Kanshi for this? Can't you do it in your Sway config file?

**Comment by sanga** [comment]
That apparently doesn’t work if I attach the external monitor after starting sway. Should I rather file a sway bug?

**Comment by emersion** [comment]
Hmm, yeah, specifying the background in sway should work for hotplugged outputs.

**Comment by sanga** [comment]
Ok. I’ll check (it’s been a while since I last tested that) and file a bug against sway if needs be

**Comment by sanga** [comment]
For the record it works OK in sway. My guess is that I hadn't quoted the identifier correctly (or then there was a bug that was subsequently fixed, but probably the problem was mine/quoting)
