### ISSUE TITLE
Occasional exit in wayland_client

### ISSUE THREAD

**Issue by Emantor** [emersion/kanshi#42]
kanshi occasionally exits with
```
Jul 22 06:38:29 dibooki kanshi[3148]: not a valid new object id (4278190112), message head(n)
```

**Comment by Emantor** [comment]
I assume this is https://gitlab.freedesktop.org/wayland/wayland/issues/86

**Comment by emersion** [comment]
This one is about multi-threaded clients. Not sure it's the same.

**Comment by Emantor** [comment]
Me neither, but I think that its still a race between client and server and fundamentally more of a wayland-client/sway issue.

**Comment by tbm** [comment]
fwiw, I just saw this too:

```
not a valid new object id (4278190080), message head(n)
```

**Comment by tbm** [comment]
I was running sway with `-d` if the logs would be useful (for my record, this happened around 13:58).

FWIW, I have an external monitor with an unreliable cable/connector and so the external monitor disappears from time to time, probably triggering this.
