### ISSUE TITLE
Add support for subpixel hinting

### ISSUE THREAD

**Issue by jsenecal** [emersion/kanshi#46]
> output <name> subpixel rgb|bgr|vrgb|vbgr|none
> 
> Manually sets the subpixel hinting for the specified output. This value is usually auto-detected, but some displays may misreport their subpixel geometry. Using the correct subpixel hinting allows for sharper text. Incorrect values will result in blurrier text. When changing this via swaymsg, some applications may need to be restarted to use the new value.

Currently complains about `unknown directive 'subpixel' in profile output ...` and fails.

Thanks !!

**Comment by emersion** [comment]
This isn't supported in kanshi, see the man page. Any reason why you want to configure subpixel in kanshi instead of sway?

**Comment by jsenecal** [comment]
One could need to configure subpixel hinting when specific displays are connected. 

Leaving those `output "Somecompany somemodel someserial" subpixel rgb` lines in the sway config for each monitor that I connect to without proper subpixel detection seems inadequate... Or perhaps it's just me?

**Comment by ammen99** [comment]
I also find it more intuitive to have subpixel in the same place as other output options such as scale.

**Comment by emersion** [comment]
The output-management protocol doesn't allow for changing the subpixel hinting. I'd rather not add this feature to the protocol.

**Comment by ghost** [comment]
This should be doable now using the "exec" feature added in #44.

**Comment by emersion** [comment]
Indeed. Closing.
