### ISSUE TITLE
Add different idle options based on profile

### ISSUE THREAD

**Issue by danyspin97** [emersion/kanshi#54]
Use case:

- when only the screen laptop is connected, lock the screen after 5 minutes, suspend after 10
- when I'm using the monitor at home, lock after 30 minutes, never suspend
- when I'm using the monitor at the workplace, lock after 5 minutes, never suspend.

This would actually require the integration of swayidle into kanshi.

**Comment by ammen99** [comment]
Just an idea, but: instead of doing this inside kanshi, why not allow getting the current profile name or whatever via kanshictl (assuming https://github.com/emersion/kanshi/pull/52 gets merged)?

**Comment by danyspin97** [comment]
Yea, it could be done. But if power management is tighted to screen profiles, why not handling this in kanshi directly?

**Comment by emersion** [comment]
I agree with @ammen99. I don't think monitor management is related to power management.
