### ISSUE TITLE
kanshi crashes: invalid arguments for zwlr_output_configuration_v1@9.enable_head

### ISSUE THREAD

**Issue by tbm** [emersion/kanshi#61]
kanshi crashes with:

```
wl_display@1: error 1: invalid arguments for zwlr_output_configuration_v1@9.enable_head
```

I assume this is another issue that will be fixed by swaywm/wlroots#1765 but I wanted to document the issue.

**Comment by emersion** [comment]
Duplicate of https://github.com/emersion/kanshi/issues/55
