### ISSUE TITLE
How to stack monitors vertically?

### ISSUE THREAD

**Issue by apiraino** [emersion/kanshi#62]
Hi!

Thank you for your work on coding ~~utilities for~~ Sway :-)

I'd like to stack my monitors vertically. Given the following kanshi config:
```
{                                                                             
    output HDMI-A-2 position 0,0 mode 2560x1440                               
    output eDP-1 position 2560,0 mode 1920x1080                               
}                                                                             
```

I'd expect `HDMI-A-2` to be "above" and move to `eDP-1` hovering the mouse cursor vertically. What actually happens is that I can switch monitors moving the cursor horizontally.

I've read the man page for `sway-output` and it looks that my config should do. Am i missing something?

```
$ swaymsg -t get_outputs 
Output eDP-1 'Unknown 0x0521 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.020000 Hz
  Position: 1920,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Available modes:
    1920x1080 @ 47.999001 Hz
    1920x1080 @ 60.020000 Hz

Output HDMI-A-2 'Dell Inc. DELL U2515H 9X2VY71J16EL'
  Current mode: 2560x1440 @ 59.951000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Available modes:
    ...
    2560x1440 @ 59.951000 Hz
```

Thanks

EDIT: possibly related to https://github.com/swaywm/sway/issues/1666#issuecomment-480017611

**Comment by xdbob** [comment]
Well, as per the man page the position is in the form of `<x>,<y>` so your config should probably look more like (assuming you want `HDMI-A-2` centered above `eDP-1`):
```
{                                                                             
    output HDMI-A-2 position 0,1080 mode 2560x1440                               
    output eDP-1 position 320,0 mode 1920x1080                               
}
```

**Comment by apiraino** [comment]
oh, you're right I was confused and missed how it works :)

Small correction to your suggestion to have `HDMI-A-2` stacked above `e-DP-1`:
```
{                                                                             
    output HDMI-A-2 position 0,0 mode 2560x1440                               
    output eDP-1 position 320,1440 mode 1920x1080                               
}
```

Thanks for the suggestion! :+1: 

Closing because I was just dumb :D
