### ISSUE TITLE
Feature Request: Variables/workspace support

### ISSUE THREAD

**Issue by faesthing** [emersion/kanshi#79]
It would be useful to support variables/workspaces to achieve something like the below. 

```
profile 1440p-left {
	set $one "Dell Inc. DELL U2715H 6VY7R72K020S"
	set $two "eDP-1"
	output $two enable mode 1920x1080 position 0,0
	output $one mode 2560x1440 position 1920,0

	workspace 1 $one
	workspace 3 $one
	workspace 5 $one
	workspace 7 $one
	workspace 9 $one
	workspace 0 $one

	workspace 2 $two
	workspace 4 $two
	workspace 6 $two
	workspace 8 $two
}
```

Ideally it would be ideal to have mostly interchangeable config support between sway config and kanshi config.

I don't know how kanshi works under the hood and don't know how difficult this would be.

**Comment by ammen99** [comment]
Seems like a duplicate issue of https://github.com/emersion/kanshi/issues/7 ? (Which is already implemented).

**Comment by emersion** [comment]
Yes, please use a script for this.
